### ISSUE TITLE
Investigate Dockerizing the web app

### ISSUE THREAD

**Issue by kcin1018** [cincyultimate/website#62]
See what it would take.  It would be much easier to deploy and CI.

**Comment by bikunem** [comment]
We use docker here at Kroger and I'm slightly familiar with it.  What I'm not familiar with is how we deploy the website.  If I can get some context on that, I can take a stab at this.

**Comment by kcin1018** [comment]
@bikunem We are just starting it where I work.  I would love to know how you are doing it at Kroger if you are able to share the info.

**Comment by kcin1018** [comment]
probably not going to do since its relatively small footprint and adding another layer would take more resources.
